language: java
sudo: true
dist: trusty
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
  - jdk_switcher use oraclejdk8
services:
  - postgresql
postgres:
  adapter: postgresql
  database: test
  username: postgres
before_script:
  - psql -c "create database test;" -U postgres
  - psql -c "create user my with password '1234';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE test TO my;" -U postgres